sulu_media:
    adapter: 'auto'
    upload:
        max_filesize: 256
    format_manager:
        default_imagine_options:
            jpeg_quality: 90
            webp_quality: 90
            avif_quality: 90
