sulu_core:
    locales:
        en: English
        de: Deutsch
        pl: Polski
    translations:
        - en
        - de
        - pl

sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
