framework:
    default_locale: '%default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%default_locale%'
        providers:

parameters:
    sulu_core.locales: ['pl', 'en', 'de']
    default_locale: 'pl'
