services:
  nginx:
    image: nginx:alpine
    container_name: partner_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - partner

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: partner_php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://sulu:sulu@mysql:3306/sulu?serverVersion=8.0
    depends_on:
      - mysql
    networks:
      - partner

  mysql:
    image: mysql:8.0
    container_name: partner_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sulu
      MYSQL_USER: sulu
      MYSQL_PASSWORD: sulu
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - partner
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: partner_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: sulu
      PMA_PASSWORD: sulu
    depends_on:
      - mysql
    networks:
      - partner

  mailhog:
    image: mailhog/mailhog
    container_name: partner_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - partner

  node:
    image: node:18-alpine
    container_name: partner_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run watch"
    networks:
      - partner

volumes:
  mysql_data:
    driver: local

networks:
  partner:
    driver: bridge
